id = "fraz-syntax-highlighting"
name = "Fraz Syntax Highlighting"
version = "0.0.1"
schema_version = 1
authors = ["FkyFrky <you@example.com>"]
description = "Syntax Highlighting for Fraz language"
repository = "https://github.com/pagnyf/fraz.git"

[grammars.fraz]
repository = "https://github.com/pagnyf/tree-sitter-fraz"
commit = "0a1a1aecd398e72123a840268e4a92e4f2809b62"
