id = "fraz-syntax-highlighting"
name = "Fraz Syntax Highlighting"
version = "0.0.1"
schema_version = 1
authors = ["FkyFrky <you@example.com>"]
description = "Syntax Highlighting for Fraz language"
repository = "https://github.com/pagnyf/fraz.git"

[grammars.fraz]
repository = "https://github.com/pagnyf/tree-sitter-fraz"
commit = "59477272b68180a9948ea878c5688f574cb16981"
